[supervisord]
nodaemon=true
user=root
pidfile=/var/run/supervisord.pid
logfile=/var/log/supervisor/supervisord.log

# PHP-FPM process
[program:php-fpm]
process_name=%(program_name)s_%(process_num)02d
command=php-fpm --nodaemonize --fpm-config /usr/local/etc/php-fpm.conf
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/php-fpm.log
stderr_logfile=/var/log/supervisor/php-fpm-error.log
numprocs=1

# Nginx process
[program:nginx]
process_name=%(program_name)s
command=/usr/sbin/nginx -g "daemon off;"
autostart=true
autorestart=true
stopasgroup=true
killasgroup=true
stdout_logfile=/var/log/supervisor/nginx.log
stderr_logfile=/var/log/supervisor/nginx-error.log

[group:web-services]
programs=php-fpm,nginx
priority=100
